[libraries]

logback-classic = {group= "ch.qos.logback", name = "logback-classic", version = "1.2.6"}
kotlin-logging = {group = "io.github.microutils", name = "kotlin-logging-jvm", version = "2.0.11"}
